-- CREATE THE DATABASE
CREATE DATABASE IF NOT EXISTS GARCON;

-- HOLDS THE BASE DATA POINTS SIMILAR TO ALL SOFTWARE COMPONENTS IN THE NIFI ECOSYSTEM
CREATE TABLE IF NOT EXISTS GARCON.DEVICE (
    DEVICE_ID BIGINT AUTO_INCREMENT,
    PRIMARY_NIC_MAC VARCHAR(255) NOT NULL,
    PRIVATE_IP VARCHAR(25) NOT NULL,
    PUBLIC_IP VARCHAR(25),
    HOSTNAME VARCHAR(255) NOT NULL,
    NUM_PROCESSORS INT NOT NULL,
    TOTAL_SYS_MEM BIGINT,
    AVAIL_SYS_MEM BIGINT,
    CONSUMED_SYS_MEM BIGINT,
    PRIMARY KEY (DEVICE_ID)
);

-- HOLDS ALL OF THE NIFI NODES ASSOCIATED WITH ACTIVE NIFI CLUSTERS UNDER GARCON
CREATE TABLE IF NOT EXISTS GARCON.NIFI_NODE (
    NODE_ID BIGINT AUTO_INCREMENT,
    NODE_URI VARCHAR(255) NOT NULL,
    DEVICE_ID BIGINT NOT NULL,
    PRIMARY KEY (NODE_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.DEVICE (DEVICE_ID)
);

-- HOLDS ALL THE MINIFI NODES (BOIH C++ AND JAVA BASED)
CREATE TABLE IF NOT EXISTS GARCON.MINIFI_DEVICE (
    MINIFI_DEVICE_ID BIGINT AUTO_INCREMENT,
    DEVICE_ID BIGINT NOT NULL,
    DEVICE_NAME VARCHAR(255),
    DEVICE_TYPE VARCHAR(4) NOT NULL,
    PRIMARY KEY (MINIFI_DEVICE_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.DEVICE (DEVICE_ID)
);

-- HOLDS ALL OF THE NIFI CLUSTERS ACTIVELY ASSOCIATED WITH GARCON. THIS ABSTRACTION REPRESENTS A GROUP OF GARCON.NIFI_NODES(S). THIS DOES NOT APPLY TO MINIFI_DEVICE(S)
CREATE TABLE IF NOT EXISTS GARCON.NIFI_CLUSTER (
    CLUSTER_ID BIGINT AUTO_INCREMENT,
    CLUSTER_NAME VARCHAR(255) NOT NULL,
    CLUSTER_DESC VARCHAR(255),
    CLUSTER_HOSTNAME VARCHAR(255) NOT NULL,
    CLUSTER_PORT VARCHAR(6) NOT NULL,
    PRIMARY KEY (CLUSTER_ID)
);

-- HOLDS THE METRIC THRESHOLDS THAT DEFINE THE PROPERTIES THAT GARCON SHOULD BE MONITORING IN A SPECIFIC NIFI INSTANCE.
CREATE TABLE IF NOT EXISTS GARCON.METRIC_THRESHOLD (
    THRESHOLD_ID BIGINT AUTO_INCREMENT,
    CLUSTER_ID BIGINT,
    THRESHOLD_NAME VARCHAR(255) NOT NULL,
    THRESHOLD_DESC VARCHAR(255),
    COMPONENT_ID VARCHAR(255) NOT NULL,
    API_URI VARCHAR(255) NOT NULL,
    PRIMARY KEY (THRESHOLD_ID),
    FOREIGN KEY (CLUSTER_ID) REFERENCES GARCON.NIFI_CLUSTER (CLUSTER_ID)
);

-- HOLDS THE THRESHOLD REACTIONS THAT WILL OCCUR BASED ON IF A METRICS THRESHOLD IS DETERMINED TO HAVE BEEN MET BY GARCON
CREATE TABLE IF NOT EXISTS GARCON.THRESHOLD_REACTION (
    REACTION_ID BIGINT AUTO_INCREMENT,
    METRIC_THRESHOLD_ID BIGINT,
    REACTION_NAME VARCHAR(255) NOT NULL,
    REACTION_DESC VARCHAR(255),
    REACTION_EVENT_CLASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (REACTION_ID),
    FOREIGN KEY (METRIC_THRESHOLD_ID) REFERENCES GARCON.METRIC_THRESHOLD (THRESHOLD_ID)
);