REATE THE DATABASE
CREATE DATABASE IF NOT EXISTS GARCON;

SET sql_mode = '';

DROP TABLE IF EXISTS `C2_DEVICE`;

CREATE TABLE `C2_DEVICE` (
  `DEVICE_ID` varchar(30) NOT NULL,
  `HOSTNAME` varchar(255) DEFAULT NULL,
  `IP` varchar(16) DEFAULT NULL,
  `MACHINE_ARCH` varchar(15) DEFAULT NULL,
  `PHYSICAL_MEM` bigint(20) DEFAULT NULL,
  `VCORES` int(11) DEFAULT NULL,
  PRIMARY KEY (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `C2_DEVICE` WRITE;
/*!40000 ALTER TABLE `C2_DEVICE` DISABLE KEYS */;

INSERT INTO `C2_DEVICE` (`DEVICE_ID`, `HOSTNAME`, `IP`, `MACHINE_ARCH`, `PHYSICAL_MEM`, `VCORES`)
VALUES
	('2166229772469413744','hw11467.fios-router.home','192.168.1.250','x86_64',17179869184,8);

/*!40000 ALTER TABLE `C2_DEVICE` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table C2_DEVICE_CONFIG
# ------------------------------------------------------------

DROP TABLE IF EXISTS `C2_DEVICE_CONFIG`;

CREATE TABLE `C2_DEVICE_CONFIG` (
  `DEVICE_CONFIG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `CONFIG_FILE` text NOT NULL,
  `CREATED_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`DEVICE_CONFIG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table C2_DEVICE_CONFIG_MAPPING
# ------------------------------------------------------------

DROP TABLE IF EXISTS `C2_DEVICE_CONFIG_MAPPING`;

CREATE TABLE `C2_DEVICE_CONFIG_MAPPING` (
  `DEVICE_CONFIG_MAPPING_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEVICE_ID` varchar(30) DEFAULT NULL,
  `DEVICE_CONFIG_ID` bigint(20) DEFAULT NULL,
  `CONFIGURED_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DEPLOYED_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`DEVICE_CONFIG_MAPPING_ID`),
  KEY `DEVICE_ID` (`DEVICE_ID`),
  KEY `DEVICE_CONFIG_ID` (`DEVICE_CONFIG_ID`),
  CONSTRAINT `c2_device_config_mapping_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `C2_DEVICE` (`DEVICE_ID`),
  CONSTRAINT `c2_device_config_mapping_ibfk_2` FOREIGN KEY (`DEVICE_CONFIG_ID`) REFERENCES `C2_DEVICE_CONFIG` (`DEVICE_CONFIG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table C2_HEARTBEATS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `C2_HEARTBEATS`;

CREATE TABLE `C2_HEARTBEATS` (
  `DEVICE_ID` varchar(30) NOT NULL,
  `OPERATION` varchar(25) NOT NULL,
  `RUNNING` tinyint(1) NOT NULL,
  `UPTIME` bigint(20) DEFAULT NULL,
  `HEARTBEAT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`DEVICE_ID`),
  CONSTRAINT `c2_heartbeats_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `C2_DEVICE` (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `C2_HEARTBEATS` WRITE;
/*!40000 ALTER TABLE `C2_HEARTBEATS` DISABLE KEYS */;

INSERT INTO `C2_HEARTBEATS` (`DEVICE_ID`, `OPERATION`, `RUNNING`, `UPTIME`, `HEARTBEAT_TIMESTAMP`)
VALUES
	('2166229772469413744','heartbeat',1,54932,'2017-07-14 18:27:41');

/*!40000 ALTER TABLE `C2_HEARTBEATS` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table C2_OPERATIONS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `C2_OPERATIONS`;

CREATE TABLE `C2_OPERATIONS` (
  `OPERATION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEVICE_ID` varchar(30) NOT NULL,
  `OPERATION` varchar(50) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `ACKED` tinyint(1) DEFAULT NULL,
  `LAST_RESPONSE_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ACK_TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `CONTENT` text,
  PRIMARY KEY (`OPERATION_ID`),
  KEY `DEVICE_ID` (`DEVICE_ID`),
  CONSTRAINT `c2_operations_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `C2_DEVICE` (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `C2_OPERATIONS` WRITE;
/*!40000 ALTER TABLE `C2_OPERATIONS` DISABLE KEYS */;

INSERT INTO `C2_OPERATIONS` (`OPERATION_ID`, `DEVICE_ID`, `OPERATION`, `NAME`, `ACKED`, `LAST_RESPONSE_TIMESTAMP`, `ACK_TIMESTAMP`, `CONTENT`)
VALUES
	(38,'2166229772469413744','START','GetFile',1,'2017-07-14 18:24:28','2017-07-14 18:24:28',''),
	(39,'2166229772469413744','STOP','GetFile',1,'2017-07-14 18:25:48','2017-07-14 18:25:48',''),
	(40,'2166229772469413744','START','GetFile',1,'2017-07-14 18:26:04','2017-07-14 18:26:04',''),
	(41,'2166229772469413744','START','GetFile',1,'2017-07-14 18:26:22','2017-07-14 18:26:22',''),
	(42,'2166229772469413744','STOP','GetFile',1,'2017-07-14 18:26:58','2017-07-14 18:26:58',''),
	(43,'2166229772469413744','START','GetFile',1,'2017-07-14 18:27:17','2017-07-14 18:27:17',''),
	(44,'2166229772469413744','STOP','GetFile',1,'2017-07-14 18:27:32','2017-07-14 18:27:32','');

/*!40000 ALTER TABLE `C2_OPERATIONS` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table C2_PROCESS_METRICS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `C2_PROCESS_METRICS`;

CREATE TABLE `C2_PROCESS_METRICS` (
  `DEVICE_ID` varchar(30) NOT NULL,
  `MEMORY_MAXRSS` bigint(20) DEFAULT NULL,
  `CPU_INVOLCS` bigint(20) DEFAULT NULL,
  `LAST_UPDATE_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`DEVICE_ID`),
  CONSTRAINT `c2_process_metrics_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `C2_DEVICE` (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `C2_PROCESS_METRICS` WRITE;
/*!40000 ALTER TABLE `C2_PROCESS_METRICS` DISABLE KEYS */;

INSERT INTO `C2_PROCESS_METRICS` (`DEVICE_ID`, `MEMORY_MAXRSS`, `CPU_INVOLCS`, `LAST_UPDATE_TIMESTAMP`)
VALUES
	('2166229772469413744',15482880,56817,'2017-07-14 18:27:41');

/*!40000 ALTER TABLE `C2_PROCESS_METRICS` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table C2_QUEUE_METRICS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `C2_QUEUE_METRICS`;

CREATE TABLE `C2_QUEUE_METRICS` (
  `DEVICE_ID` varchar(30) NOT NULL,
  `QUEUE_METRICS_ID` varchar(255) NOT NULL,
  `DATA_SIZE` bigint(20) DEFAULT NULL,
  `DATA_SIZE_MAX` bigint(20) DEFAULT NULL,
  `QUEUED` bigint(20) DEFAULT NULL,
  `QUEUED_MAX` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DEVICE_ID`,`QUEUE_METRICS_ID`),
  CONSTRAINT `c2_queue_metrics_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `C2_DEVICE` (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `C2_QUEUE_METRICS` WRITE;
/*!40000 ALTER TABLE `C2_QUEUE_METRICS` DISABLE KEYS */;

INSERT INTO `C2_QUEUE_METRICS` (`DEVICE_ID`, `QUEUE_METRICS_ID`, `DATA_SIZE`, `DATA_SIZE_MAX`, `QUEUED`, `QUEUED_MAX`)
VALUES
	('2166229772469413744','FromNiFiNawwhatIMean',0,0,0,0),
	('2166229772469413744','TransferFilesToRPG2',3888,0,3267,0);

/*!40000 ALTER TABLE `C2_QUEUE_METRICS` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table C2_COMPONENT_STATUS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `C2_COMPONENT_STATUS`;

CREATE TABLE `C2_COMPONENT_STATUS` (
  `DEVICE_ID` varchar(255) NOT NULL DEFAULT '',
  `COMPONENT` varchar(255) NOT NULL DEFAULT '',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`DEVICE_ID`,`COMPONENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `C2_COMPONENT_STATUS` WRITE;
/*!40000 ALTER TABLE `C2_COMPONENT_STATUS` DISABLE KEYS */;

INSERT INTO `C2_COMPONENT_STATUS` (`DEVICE_ID`, `COMPONENT`, `status`)
VALUES
	('2166229772469413744','FlowController',1),
	('2166229772469413744','fromnifi',1),
	('2166229772469413744','GetFile',0),
	('2166229772469413744','Loggit',1),
	('2166229772469413744','tominifi',1);

/*!40000 ALTER TABLE `C2_COMPONENT_STATUS` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table CONNECTION_STATUS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `CONNECTION_STATUS`;

CREATE TABLE `CONNECTION_STATUS` (
  `CONNECTION_STATUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEVICE_ID` varchar(25) NOT NULL,
  `ID` varchar(255) NOT NULL,
  `GROUP_ID` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `SOURCE_ID` varchar(255) NOT NULL,
  `SOURCE_NAME` varchar(255) NOT NULL,
  `DESTINATION_ID` varchar(255) NOT NULL,
  `DESTINATION_NAME` varchar(255) NOT NULL,
  `BACK_PRESSURE_DATA_SIZE_THRESHOLD` varchar(255) NOT NULL,
  `BACK_PRESSURE_BYTES_THRESHOLD` bigint(20) DEFAULT NULL,
  `BACK_PRESSURE_OBJECT_THRESHOLD` bigint(20) DEFAULT NULL,
  `INPUT_COUNT` int(11) DEFAULT NULL,
  `INPUT_BYTES` bigint(20) DEFAULT NULL,
  `QUEUED_COUNT` int(11) DEFAULT NULL,
  `QUEUED_BYTES` bigint(20) DEFAULT NULL,
  `OUTPUT_COUNT` int(11) DEFAULT NULL,
  `OUTPUT_BYTES` bigint(20) DEFAULT NULL,
  `MAX_QUEUED_COUNT` int(11) DEFAULT NULL,
  `MAX_QUEUED_BYTES` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CONNECTION_STATUS_ID`),
  KEY `DEVICE_ID` (`DEVICE_ID`),
  CONSTRAINT `connection_status_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `DEVICE` (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table DEVICE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `DEVICE`;

CREATE TABLE `DEVICE` (
  `DEVICE_ID` varchar(25) NOT NULL,
  `IP` varchar(25) DEFAULT NULL,
  `HOSTNAME` varchar(255) NOT NULL,
  `NUM_PROCESSORS` int(11) NOT NULL,
  `TOTAL_SYS_MEM` bigint(20) DEFAULT NULL,
  `AVAIL_SYS_MEM` bigint(20) DEFAULT NULL,
  `CONSUMED_SYS_MEM` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table METRIC_THRESHOLD
# ------------------------------------------------------------

DROP TABLE IF EXISTS `METRIC_THRESHOLD`;

CREATE TABLE `METRIC_THRESHOLD` (
  `THRESHOLD_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLUSTER_ID` bigint(20) DEFAULT NULL,
  `THRESHOLD_NAME` varchar(255) NOT NULL,
  `THRESHOLD_DESC` varchar(255) DEFAULT NULL,
  `COMPONENT_ID` varchar(255) NOT NULL,
  `API_URI` varchar(255) NOT NULL,
  PRIMARY KEY (`THRESHOLD_ID`),
  KEY `CLUSTER_ID` (`CLUSTER_ID`),
  CONSTRAINT `metric_threshold_ibfk_1` FOREIGN KEY (`CLUSTER_ID`) REFERENCES `NIFI_CLUSTER` (`CLUSTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table MINIFI_DEVICE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `MINIFI_DEVICE`;

CREATE TABLE `MINIFI_DEVICE` (
  `MINIFI_DEVICE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEVICE_ID` varchar(25) NOT NULL,
  `DEVICE_NAME` varchar(255) DEFAULT NULL,
  `DEVICE_TYPE` varchar(4) NOT NULL,
  PRIMARY KEY (`MINIFI_DEVICE_ID`),
  KEY `DEVICE_ID` (`DEVICE_ID`),
  CONSTRAINT `minifi_device_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `DEVICE` (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table NIFI_CLUSTER
# ------------------------------------------------------------

DROP TABLE IF EXISTS `NIFI_CLUSTER`;

CREATE TABLE `NIFI_CLUSTER` (
  `CLUSTER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLUSTER_NAME` varchar(255) NOT NULL,
  `CLUSTER_DESC` varchar(255) DEFAULT NULL,
  `CLUSTER_HOSTNAME` varchar(255) NOT NULL,
  `CLUSTER_PORT` varchar(6) NOT NULL,
  PRIMARY KEY (`CLUSTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table NIFI_NODE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `NIFI_NODE`;

CREATE TABLE `NIFI_NODE` (
  `NODE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NODE_URI` varchar(255) NOT NULL,
  `DEVICE_ID` varchar(25) NOT NULL,
  PRIMARY KEY (`NODE_ID`),
  KEY `DEVICE_ID` (`DEVICE_ID`),
  CONSTRAINT `nifi_node_ibfk_1` FOREIGN KEY (`DEVICE_ID`) REFERENCES `DEVICE` (`DEVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



# Dump of table THRESHOLD_REACTION
# ------------------------------------------------------------

DROP TABLE IF EXISTS `THRESHOLD_REACTION`;

CREATE TABLE `THRESHOLD_REACTION` (
  `REACTION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `METRIC_THRESHOLD_ID` bigint(20) DEFAULT NULL,
  `REACTION_NAME` varchar(255) NOT NULL,
  `REACTION_DESC` varchar(255) DEFAULT NULL,
  `REACTION_EVENT_CLASS` varchar(255) NOT NULL,
  PRIMARY KEY (`REACTION_ID`),
  KEY `METRIC_THRESHOLD_ID` (`METRIC_THRESHOLD_ID`),
  CONSTRAINT `threshold_reaction_ibfk_1` FOREIGN KEY (`METRIC_THRESHOLD_ID`) REFERENCES `METRIC_THRESHOLD` (`THRESHOLD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



