-- CREATE THE DATABASE
CREATE DATABASE IF NOT EXISTS GARCON;

-- HOLDS THE BASE DATA POINTS SIMILAR TO ALL SOFTWARE COMPONENTS IN THE NIFI ECOSYSTEM
CREATE TABLE IF NOT EXISTS GARCON.DEVICE (
    DEVICE_ID VARCHAR(25),
    IP VARCHAR(25),
    HOSTNAME VARCHAR(255) NOT NULL,
    NUM_PROCESSORS INT NOT NULL,
    TOTAL_SYS_MEM BIGINT,
    AVAIL_SYS_MEM BIGINT,
    CONSUMED_SYS_MEM BIGINT,
    PRIMARY KEY (DEVICE_ID)
);

-- HOLDS ALL OF THE NIFI NODES ASSOCIATED WITH ACTIVE NIFI CLUSTERS UNDER GARCON
CREATE TABLE IF NOT EXISTS GARCON.NIFI_NODE (
    NODE_ID BIGINT AUTO_INCREMENT,
    NODE_URI VARCHAR(255) NOT NULL,
    DEVICE_ID VARCHAR(25) NOT NULL,
    PRIMARY KEY (NODE_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.DEVICE (DEVICE_ID)
);

-- HOLDS ALL THE MINIFI NODES (BOIH C++ AND JAVA BASED)
CREATE TABLE IF NOT EXISTS GARCON.MINIFI_DEVICE (
    MINIFI_DEVICE_ID BIGINT AUTO_INCREMENT,
    DEVICE_ID VARCHAR(25) NOT NULL,
    DEVICE_NAME VARCHAR(255),
    DEVICE_TYPE VARCHAR(4) NOT NULL,
    PRIMARY KEY (MINIFI_DEVICE_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.DEVICE (DEVICE_ID)
);

-- HOLDS ALL OF THE NIFI CLUSTERS ACTIVELY ASSOCIATED WITH GARCON. THIS ABSTRACTION REPRESENTS A GROUP OF GARCON.NIFI_NODES(S). THIS DOES NOT APPLY TO MINIFI_DEVICE(S)
CREATE TABLE IF NOT EXISTS GARCON.NIFI_CLUSTER (
    CLUSTER_ID BIGINT AUTO_INCREMENT,
    CLUSTER_NAME VARCHAR(255) NOT NULL,
    CLUSTER_DESC VARCHAR(255),
    CLUSTER_HOSTNAME VARCHAR(255) NOT NULL,
    CLUSTER_PORT VARCHAR(6) NOT NULL,
    PRIMARY KEY (CLUSTER_ID)
);

-- HOLDS THE METRIC THRESHOLDS THAT DEFINE THE PROPERTIES THAT GARCON SHOULD BE MONITORING IN A SPECIFIC NIFI INSTANCE.
CREATE TABLE IF NOT EXISTS GARCON.METRIC_THRESHOLD (
    THRESHOLD_ID BIGINT AUTO_INCREMENT,
    CLUSTER_ID BIGINT,
    THRESHOLD_NAME VARCHAR(255) NOT NULL,
    THRESHOLD_DESC VARCHAR(255),
    COMPONENT_ID VARCHAR(255) NOT NULL,
    API_URI VARCHAR(255) NOT NULL,
    PRIMARY KEY (THRESHOLD_ID),
    FOREIGN KEY (CLUSTER_ID) REFERENCES GARCON.NIFI_CLUSTER (CLUSTER_ID)
);

-- HOLDS THE THRESHOLD REACTIONS THAT WILL OCCUR BASED ON IF A METRICS THRESHOLD IS DETERMINED TO HAVE BEEN MET BY GARCON
CREATE TABLE IF NOT EXISTS GARCON.THRESHOLD_REACTION (
    REACTION_ID BIGINT AUTO_INCREMENT,
    METRIC_THRESHOLD_ID BIGINT,
    REACTION_NAME VARCHAR(255) NOT NULL,
    REACTION_DESC VARCHAR(255),
    REACTION_EVENT_CLASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (REACTION_ID),
    FOREIGN KEY (METRIC_THRESHOLD_ID) REFERENCES GARCON.METRIC_THRESHOLD (THRESHOLD_ID)
);

-- HOLDS THE CONNECTIONSTATUS FOR A MONITORED DEVICE.
CREATE TABLE IF NOT EXISTS GARCON.CONNECTION_STATUS (
    CONNECTION_STATUS_ID BIGINT AUTO_INCREMENT,
    DEVICE_ID VARCHAR(25) NOT NULL,
    ID VARCHAR(255) NOT NULL,
    GROUP_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_NAME VARCHAR(255) NOT NULL,
    DESTINATION_ID VARCHAR(255) NOT NULL,
    DESTINATION_NAME VARCHAR(255) NOT NULL,
    BACK_PRESSURE_DATA_SIZE_THRESHOLD VARCHAR(255) NOT NULL,
    BACK_PRESSURE_BYTES_THRESHOLD BIGINT,
    BACK_PRESSURE_OBJECT_THRESHOLD BIGINT,
    INPUT_COUNT INT,
    INPUT_BYTES BIGINT,
    QUEUED_COUNT INT,
    QUEUED_BYTES BIGINT,
    OUTPUT_COUNT INT,
    OUTPUT_BYTES BIGINT,
    MAX_QUEUED_COUNT INT,
    MAX_QUEUED_BYTES BIGINT,
    PRIMARY KEY (CONNECTION_STATUS_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.DEVICE (DEVICE_ID)
);


-- BEGIN C2 SPECIFIC TABLES. THESE TABLES CAN LIKELY BE MERGED INTO THE TABLES ABOVE ONCE THE FINAL DESIGN HAS BEEN AGREED UPON.

-- HOLDS THE MINIFI CPP DEVICE INFORMATION
CREATE TABLE IF NOT EXISTS GARCON.C2_DEVICE (
    DEVICE_ID VARCHAR(30),
    HOSTNAME VARCHAR(255),
    IP VARCHAR(16),
    MACHINE_ARCH VARCHAR(15),
    PHYSICAL_MEM BIGINT,
    VCORES INT,
    PRIMARY KEY (DEVICE_ID)
);

-- HOLDS THE METRICS RECEIVED FROM THE MINIFI DEVICE
CREATE TABLE IF NOT EXISTS GARCON.C2_QUEUE_METRICS (
    DEVICE_ID VARCHAR(30),
    QUEUE_METRICS_ID VARCHAR(255),        -- THIS WILL BE THE NAME OF THE CONNECTION
    DATA_SIZE BIGINT,
    DATA_SIZE_MAX BIGINT,
    QUEUED BIGINT,
    QUEUED_MAX BIGINT,
    PRIMARY KEY (DEVICE_ID, QUEUE_METRICS_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.C2_DEVICE (DEVICE_ID)
);

-- HOLDS THE PROCESS METRICS FROM THE MINIFI DEVICE
CREATE TABLE IF NOT EXISTS GARCON.C2_PROCESS_METRICS (
    DEVICE_ID VARCHAR(30),
    MEMORY_MAXRSS BIGINT,
    CPU_INVOLCS BIGINT,
    LAST_UPDATE_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (DEVICE_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.C2_DEVICE (DEVICE_ID)
);

-- HOLDS THE MINIFI-CPP C2AGENT HEARTBEATS
CREATE TABLE IF NOT EXISTS GARCON.C2_HEARTBEATS (
    DEVICE_ID VARCHAR(30),
    OPERATION VARCHAR(25) NOT NULL,
    RUNNING BOOLEAN NOT NULL,
    UPTIME BIGINT,
    HEARTBEAT_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (DEVICE_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.C2_DEVICE (DEVICE_ID)
);

-- HOLDS THE PENDING OPERATIONS TO BE SENT TO THE CLIENT
CREATE TABLE IF NOT EXISTS GARCON.C2_OPERATIONS (
    OPERATION_ID BIGINT AUTO_INCREMENT,
    DEVICE_ID VARCHAR(30) NOT NULL,
    OPERATION VARCHAR(50) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ACKED BOOL,
    ACK_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (OPERATION_ID),
    FOREIGN KEY (DEVICE_ID) REFERENCES GARCON.C2_DEVICE (DEVICE_ID)
);