CREATE DATABASE IF NOT EXISTS DEVICE_REGISTRY;
USE DEVICE_REGISTRY;

-- Create the DEVICE_REGISTRY tables.
CREATE TABLE IF NOT EXISTS DEVICE_REGISTRY.DEVICE (
    ID INT NOT NULL auto_increment primary key,
    INTERNAL_IP NOT NULL VARCHAR(255),
    EXTERNAL_IP VARCHAR(255),
    PRIMARY_NIC_MAC NOT NULL VARCHAR(255),
    HOSTNAME NOT NULL VARCHAR(255),
    NUM_PROCESSORS SMALLINT,
    JVM_FREE_MEMORY BIGINT,
    JVM_TOTAL_MEMORY BIGINT,
    JVM_MAX_MEMORY BIGINT
);