CREATE DATABASE IF NOT EXISTS GARCON;
USE GARCON;

-- Create the DEVICE_REGISTRY tables.
CREATE TABLE IF NOT EXISTS GARCON.DEVICE (
    ID INT NOT NULL auto_increment primary key,
    INTERNAL_IP VARCHAR(255) NOT NULL,
    EXTERNAL_IP VARCHAR(255),
    PRIMARY_NIC_MAC VARCHAR(255) NOT NULL,
    HOSTNAME VARCHAR(255) NOT NULL,
    NUM_PROCESSORS SMALLINT,
    JVM_FREE_MEMORY BIGINT,
    JVM_TOTAL_MEMORY BIGINT,
    JVM_MAX_MEMORY BIGINT
);