CREATE DATABASE IF NOT EXISTS GARCON;

CREATE TABLE IF NOT EXISTS GARCON.PROV_EVENTS (
    EVENTID VARCHAR PRIMARY KEY,
    EVENTORDINAL VARCHAR,
    EVENTTYPE VARCHAR,
    TIMESTAMPMILLIS VARCHAR,
    TIMESTAMP VARCHAR,
    DURATIONMILLIS VARCHAR,
    LINEAGESTART VARCHAR,
    DETAILS VARCHAR,
    COMPONENTID VARCHAR,
    COMPONENTTYPE VARCHAR,
    COMPONENTNAME VARCHAR,
    ENTITYID VARCHAR,
    ENTITYTYPE VARCHAR,
    ENTITYSIZE VARCHAR,
    UPDATEDATTRIBUTES VARCHAR,
    PREVIOUSATTRIBUTES VARCHAR,
    ACTORHOSTNAME VARCHAR,
    CONTENTURI VARCHAR,
    PREVIOUSCONTENTURI VARCHAR,
    PARENTIDS VARCHAR,
    CHILDIDS VARCHAR,
    PLATFORM VARCHAR,
    APPLICATION VARCHAR,
    UUID VARCHAR
);